const requestBody = {
    "additionalText1": "Additional Text 1",
    "additionalText2": null,
    "amount": 800,
    "assets": null,
    "assignment": "assignments",
    "bankAccountId": "5pkneSiCAtvBmODa",
    "businessTransactionId": "7ggx4ahIyyrolp2N",
    "cjDocNo": "1",
    "controllingArea": "1000",
    "costCentreId": "hIdTkK0OTPPPlX0Z",
    "customerId": "_2O4iwje-Rh8HDhj",
    "documentDate": "2023-05-09",
    "documentStatus": "Saved",
    "employeeId": null,
    "glAccountId": "jHakE061zlogJBOZ",
    "houseBank": "7nwVvsy8aRSsQcUX",
    "internalCashJournal": "2",
    "netAmount": 800,
    "orderNo": null,
    "pettyCashType": "Receipt",
    "plantId": "DwlkCKZrbY8SA23g",
    "postingDate": "2023-05-09T04:23:54.021Z",
    "profitCentreId": "UJkpjaZBhu6PbcV8",
    "profitabilitySegmentNo": null,
    "receiptRecipient": "receipt",
    "refDocNo": "1001",
    "referenceDate": null,
    "segmentId": "c3Qw_cSDc9HIs2vl",
    "subNumber": null,
    "taxBaseAmount": 800,
    "taxCodeId": "Rp5Kdvlmn6WhKPdY",
    "taxRate": 0,
    "text": "text",
    "transactionType": null,
    "vendorId": null,
    "cashJournalId": "o2kHOE6HrgrgaGjH",
    "fromDate": "2023-05-09T03:23:54.021Z",
    "toDate": "2023-05-09T03:23:54.021Z"
};

export {requestBody}