require('dotenv').config();

module.exports = {
  local: {
    database: process.env.LOCAL_DB,
    username: process.env.LOCAL_DB_USER,
    password: process.env.LOCAL_DB_PASS,
    dialect: 'mssql',
    host: process.env.LOCAL_HOST,
    serverPort: process.env.LOCAL_PORT,
    logging: console.log,
    autoBackup: false,
    sessionSecret: process.env.SESSION_SECRET_KEY,
  },
  dev: {
    database: process.env.DEV_DB,
    username: process.env.DEV_DB_USER,
    password: process.env.DEV_DB_PASS,
    dialect: 'mssql',
    host: process.env.DEV_HOST,
    serverPort: process.env.DEV_PORT,
    logging: console.log,
    autoBackup: false,
    sessionSecret: process.env.SESSION_SECRET_KEY,
  },
  uat: {
    database: process.env.UAT_DB,
    username: process.env.UAT_DB_USER,
    password: process.env.UAT_DB_PASS,
    dialect: 'mssql',
    host: process.env.UAT_HOST,
    serverPort: process.env.UAT_PORT,
    logging: false,
    autoBackup: true,
    sessionSecret: process.env.SESSION_SECRET_KEY,
  },
  prod: {
    database: process.env.PROD_DB,
    username: process.env.PROD_DB_USER,
    password: process.env.PROD_DB_PASS,
    dialect: 'mssql',
    host: process.env.PROD_HOST,
    serverPort: process.env.PROD_PORT,
    logging: false,
    autoBackup: true,
    sessionSecret: process.env.SESSION_SECRET_KEY,
  },
};
