name: Lint, Test & Build

on:
  pull_request:
    branches:
      - master
      - development
      - uat
  push:
    branches:
      - master
      - development
      - uat

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        env:
          TEST_DB: ${{ secrets.TEST_DB }}
          TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
          TEST_DB_PASS: ${{ secrets.TEST_DB_PASS }}
          TEST_HOST: ${{ secrets.TEST_HOST }}
          TEST_PORT: ${{ secrets.TEST_PORT }}
          SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          TEST_MAIL_HOST: ${{ secrets.TEST_MAIL_HOST }}
          TEST_MAIL_USER: ${{ secrets.TEST_MAIL_USER }}
          TEST_MAIL_PASS: ${{ secrets.TEST_MAIL_PASS }}
          TEST_MAIL_FROM: ${{ secrets.TEST_MAIL_FROM }}
          TEST_APP_BASE_URL: ${{ secrets.TEST_APP_BASE_URL }}
        run: npm run test

      - name: Run build
        run: npm run build
