name: Test & Build

on:
  pull_request:
    branches:
      - master
      - development
      - uat
  push:
    branches:
      - master
      - development
      - uat

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      # - name: Run linting
      #   run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Run build
        run: npm run build
